# Generated by Django 5.1 on 2024-10-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_produto_codigoproduto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='imagemProduto',
            new_name='imgProduto',
        ),
    ]
